# coding: utf-8

"""
    Quay Frontend

    This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@quay.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import quay
from api.mirror_api import MirrorApi  # noqa: E501
from quay.rest import ApiException


class TestMirrorApi(unittest.TestCase):
    """MirrorApi unit test stubs"""

    def setUp(self):
        self.api = api.mirror_api.MirrorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_change_repo_mirror_config(self):
        """Test case for change_repo_mirror_config

        """
        pass

    def test_create_repo_mirror_config(self):
        """Test case for create_repo_mirror_config

        """
        pass

    def test_get_repo_mirror_config(self):
        """Test case for get_repo_mirror_config

        """
        pass

    def test_sync_cancel(self):
        """Test case for sync_cancel

        """
        pass

    def test_sync_now(self):
        """Test case for sync_now

        """
        pass


if __name__ == '__main__':
    unittest.main()
