# coding: utf-8

"""
    Quay Frontend

    This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@quay.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import quay
from api.image_api import ImageApi  # noqa: E501
from quay.rest import ApiException


class TestImageApi(unittest.TestCase):
    """ImageApi unit test stubs"""

    def setUp(self):
        self.api = api.image_api.ImageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_image(self):
        """Test case for get_image

        """
        pass

    def test_list_repository_images(self):
        """Test case for list_repository_images

        """
        pass


if __name__ == '__main__':
    unittest.main()
