# coding: utf-8

"""
    Quay Frontend

    This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@quay.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import quay
from api.superuser_api import SuperuserApi  # noqa: E501
from quay.rest import ApiException


class TestSuperuserApi(unittest.TestCase):
    """SuperuserApi unit test stubs"""

    def setUp(self):
        self.api = api.superuser_api.SuperuserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_approve_service_key(self):
        """Test case for approve_service_key

        """
        pass

    def test_change_organization(self):
        """Test case for change_organization

        """
        pass

    def test_create_install_user(self):
        """Test case for create_install_user

        """
        pass

    def test_create_service_key(self):
        """Test case for create_service_key

        """
        pass

    def test_delete_organization(self):
        """Test case for delete_organization

        """
        pass

    def test_delete_service_key(self):
        """Test case for delete_service_key

        """
        pass

    def test_get_repo_build_logs_super_user(self):
        """Test case for get_repo_build_logs_super_user

        """
        pass

    def test_get_repo_build_status_super_user(self):
        """Test case for get_repo_build_status_super_user

        """
        pass

    def test_get_repo_build_super_user(self):
        """Test case for get_repo_build_super_user

        """
        pass

    def test_get_service_key(self):
        """Test case for get_service_key

        """
        pass

    def test_list_all_users(self):
        """Test case for list_all_users

        """
        pass

    def test_list_service_keys(self):
        """Test case for list_service_keys

        """
        pass

    def test_update_service_key(self):
        """Test case for update_service_key

        """
        pass


if __name__ == '__main__':
    unittest.main()
