# coding: utf-8

"""
    Quay Frontend

    This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@quay.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import quay
from api.manifest_api import ManifestApi  # noqa: E501
from quay.rest import ApiException


class TestManifestApi(unittest.TestCase):
    """ManifestApi unit test stubs"""

    def setUp(self):
        self.api = api.manifest_api.ManifestApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_manifest_label(self):
        """Test case for add_manifest_label

        """
        pass

    def test_delete_manifest_label(self):
        """Test case for delete_manifest_label

        """
        pass

    def test_get_manifest_label(self):
        """Test case for get_manifest_label

        """
        pass

    def test_get_repo_manifest(self):
        """Test case for get_repo_manifest

        """
        pass

    def test_list_manifest_labels(self):
        """Test case for list_manifest_labels

        """
        pass


if __name__ == '__main__':
    unittest.main()
