# coding: utf-8

"""
    Quay Frontend

    This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@quay.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import quay
from api.globalmessages_api import GlobalmessagesApi  # noqa: E501
from quay.rest import ApiException


class TestGlobalmessagesApi(unittest.TestCase):
    """GlobalmessagesApi unit test stubs"""

    def setUp(self):
        self.api = api.globalmessages_api.GlobalmessagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_global_message(self):
        """Test case for create_global_message

        """
        pass

    def test_delete_global_message(self):
        """Test case for delete_global_message

        """
        pass

    def test_get_global_messages(self):
        """Test case for get_global_messages

        """
        pass


if __name__ == '__main__':
    unittest.main()
