# coding: utf-8

"""
    Quay Frontend

    This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@quay.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import quay
from api.user_api import UserApi  # noqa: E501
from quay.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = api.user_api.UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_star(self):
        """Test case for create_star

        """
        pass

    def test_delete_star(self):
        """Test case for delete_star

        """
        pass

    def test_get_logged_in_user(self):
        """Test case for get_logged_in_user

        """
        pass

    def test_get_user_information(self):
        """Test case for get_user_information

        """
        pass

    def test_list_starred_repos(self):
        """Test case for list_starred_repos

        """
        pass


if __name__ == '__main__':
    unittest.main()
