# coding: utf-8

"""
    Quay Frontend

    This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@quay.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import quay
from api.trigger_api import TriggerApi  # noqa: E501
from quay.rest import ApiException


class TestTriggerApi(unittest.TestCase):
    """TriggerApi unit test stubs"""

    def setUp(self):
        self.api = api.trigger_api.TriggerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_activate_build_trigger(self):
        """Test case for activate_build_trigger

        """
        pass

    def test_delete_build_trigger(self):
        """Test case for delete_build_trigger

        """
        pass

    def test_get_build_trigger(self):
        """Test case for get_build_trigger

        """
        pass

    def test_list_build_triggers(self):
        """Test case for list_build_triggers

        """
        pass

    def test_list_trigger_recent_builds(self):
        """Test case for list_trigger_recent_builds

        """
        pass

    def test_manually_start_build_trigger(self):
        """Test case for manually_start_build_trigger

        """
        pass

    def test_update_build_trigger(self):
        """Test case for update_build_trigger

        """
        pass


if __name__ == '__main__':
    unittest.main()
