# coding: utf-8

"""
    Quay Frontend

    This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@quay.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import quay
from api.appspecifictokens_api import AppspecifictokensApi  # noqa: E501
from quay.rest import ApiException


class TestAppspecifictokensApi(unittest.TestCase):
    """AppspecifictokensApi unit test stubs"""

    def setUp(self):
        self.api = api.appspecifictokens_api.AppspecifictokensApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_app_token(self):
        """Test case for create_app_token

        """
        pass

    def test_get_app_token(self):
        """Test case for get_app_token

        """
        pass

    def test_list_app_tokens(self):
        """Test case for list_app_tokens

        """
        pass

    def test_revoke_app_token(self):
        """Test case for revoke_app_token

        """
        pass


if __name__ == '__main__':
    unittest.main()
