# coding: utf-8

"""
    Quay Frontend

    This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@quay.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import quay
from api.repositorynotification_api import RepositorynotificationApi  # noqa: E501
from quay.rest import ApiException


class TestRepositorynotificationApi(unittest.TestCase):
    """RepositorynotificationApi unit test stubs"""

    def setUp(self):
        self.api = api.repositorynotification_api.RepositorynotificationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_repo_notification(self):
        """Test case for create_repo_notification

        """
        pass

    def test_delete_repo_notification(self):
        """Test case for delete_repo_notification

        """
        pass

    def test_get_repo_notification(self):
        """Test case for get_repo_notification

        """
        pass

    def test_list_repo_notifications(self):
        """Test case for list_repo_notifications

        """
        pass

    def test_reset_repository_notification_failures(self):
        """Test case for reset_repository_notification_failures

        """
        pass

    def test_test_repo_notification(self):
        """Test case for test_repo_notification

        """
        pass


if __name__ == '__main__':
    unittest.main()
