# coding: utf-8

"""
    Quay Frontend

    This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@quay.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import quay
from api.logs_api import LogsApi  # noqa: E501
from quay.rest import ApiException


class TestLogsApi(unittest.TestCase):
    """LogsApi unit test stubs"""

    def setUp(self):
        self.api = api.logs_api.LogsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_export_org_logs(self):
        """Test case for export_org_logs

        """
        pass

    def test_export_repo_logs(self):
        """Test case for export_repo_logs

        """
        pass

    def test_export_user_logs(self):
        """Test case for export_user_logs

        """
        pass

    def test_get_aggregate_org_logs(self):
        """Test case for get_aggregate_org_logs

        """
        pass

    def test_get_aggregate_repo_logs(self):
        """Test case for get_aggregate_repo_logs

        """
        pass

    def test_get_aggregate_user_logs(self):
        """Test case for get_aggregate_user_logs

        """
        pass

    def test_list_org_logs(self):
        """Test case for list_org_logs

        """
        pass

    def test_list_repo_logs(self):
        """Test case for list_repo_logs

        """
        pass

    def test_list_user_logs(self):
        """Test case for list_user_logs

        """
        pass


if __name__ == '__main__':
    unittest.main()
