# coding: utf-8

"""
    Quay Frontend

    This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@quay.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class NewUser(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'username': 'str',
        'password': 'str',
        'email': 'str',
        'invite_code': 'str',
        'recaptcha_response': 'str'
    }

    attribute_map = {
        'username': 'username',
        'password': 'password',
        'email': 'email',
        'invite_code': 'invite_code',
        'recaptcha_response': 'recaptcha_response'
    }

    def __init__(self, username=None, password=None, email=None, invite_code=None, recaptcha_response=None):  # noqa: E501
        """NewUser - a model defined in Swagger"""  # noqa: E501
        self._username = None
        self._password = None
        self._email = None
        self._invite_code = None
        self._recaptcha_response = None
        self.discriminator = None
        self.username = username
        self.password = password
        if email is not None:
            self.email = email
        if invite_code is not None:
            self.invite_code = invite_code
        if recaptcha_response is not None:
            self.recaptcha_response = recaptcha_response

    @property
    def username(self):
        """Gets the username of this NewUser.  # noqa: E501

        The user's username  # noqa: E501

        :return: The username of this NewUser.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this NewUser.

        The user's username  # noqa: E501

        :param username: The username of this NewUser.  # noqa: E501
        :type: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def password(self):
        """Gets the password of this NewUser.  # noqa: E501

        The user's password  # noqa: E501

        :return: The password of this NewUser.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this NewUser.

        The user's password  # noqa: E501

        :param password: The password of this NewUser.  # noqa: E501
        :type: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def email(self):
        """Gets the email of this NewUser.  # noqa: E501

        The user's email address  # noqa: E501

        :return: The email of this NewUser.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this NewUser.

        The user's email address  # noqa: E501

        :param email: The email of this NewUser.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def invite_code(self):
        """Gets the invite_code of this NewUser.  # noqa: E501

        The optional invite code  # noqa: E501

        :return: The invite_code of this NewUser.  # noqa: E501
        :rtype: str
        """
        return self._invite_code

    @invite_code.setter
    def invite_code(self, invite_code):
        """Sets the invite_code of this NewUser.

        The optional invite code  # noqa: E501

        :param invite_code: The invite_code of this NewUser.  # noqa: E501
        :type: str
        """

        self._invite_code = invite_code

    @property
    def recaptcha_response(self):
        """Gets the recaptcha_response of this NewUser.  # noqa: E501

        The (may be disabled) recaptcha response code for verification  # noqa: E501

        :return: The recaptcha_response of this NewUser.  # noqa: E501
        :rtype: str
        """
        return self._recaptcha_response

    @recaptcha_response.setter
    def recaptcha_response(self, recaptcha_response):
        """Sets the recaptcha_response of this NewUser.

        The (may be disabled) recaptcha response code for verification  # noqa: E501

        :param recaptcha_response: The recaptcha_response of this NewUser.  # noqa: E501
        :type: str
        """

        self._recaptcha_response = recaptcha_response

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NewUser, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NewUser):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
