# coding: utf-8

"""
    Quay Frontend

    This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@quay.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class UpdateUser(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'username': 'str',
        'invoice_email': 'bool',
        'password': 'str',
        'email': 'str',
        'tag_expiration_s': 'int'
    }

    attribute_map = {
        'username': 'username',
        'invoice_email': 'invoice_email',
        'password': 'password',
        'email': 'email',
        'tag_expiration_s': 'tag_expiration_s'
    }

    def __init__(self, username=None, invoice_email=None, password=None, email=None, tag_expiration_s=None):  # noqa: E501
        """UpdateUser - a model defined in Swagger"""  # noqa: E501
        self._username = None
        self._invoice_email = None
        self._password = None
        self._email = None
        self._tag_expiration_s = None
        self.discriminator = None
        if username is not None:
            self.username = username
        if invoice_email is not None:
            self.invoice_email = invoice_email
        if password is not None:
            self.password = password
        if email is not None:
            self.email = email
        if tag_expiration_s is not None:
            self.tag_expiration_s = tag_expiration_s

    @property
    def username(self):
        """Gets the username of this UpdateUser.  # noqa: E501

        The user's username  # noqa: E501

        :return: The username of this UpdateUser.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this UpdateUser.

        The user's username  # noqa: E501

        :param username: The username of this UpdateUser.  # noqa: E501
        :type: str
        """

        self._username = username

    @property
    def invoice_email(self):
        """Gets the invoice_email of this UpdateUser.  # noqa: E501

        Whether the user desires to receive an invoice email.  # noqa: E501

        :return: The invoice_email of this UpdateUser.  # noqa: E501
        :rtype: bool
        """
        return self._invoice_email

    @invoice_email.setter
    def invoice_email(self, invoice_email):
        """Sets the invoice_email of this UpdateUser.

        Whether the user desires to receive an invoice email.  # noqa: E501

        :param invoice_email: The invoice_email of this UpdateUser.  # noqa: E501
        :type: bool
        """

        self._invoice_email = invoice_email

    @property
    def password(self):
        """Gets the password of this UpdateUser.  # noqa: E501

        The user's password  # noqa: E501

        :return: The password of this UpdateUser.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this UpdateUser.

        The user's password  # noqa: E501

        :param password: The password of this UpdateUser.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def email(self):
        """Gets the email of this UpdateUser.  # noqa: E501

        The user's email address  # noqa: E501

        :return: The email of this UpdateUser.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UpdateUser.

        The user's email address  # noqa: E501

        :param email: The email of this UpdateUser.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def tag_expiration_s(self):
        """Gets the tag_expiration_s of this UpdateUser.  # noqa: E501

        The number of seconds for tag expiration  # noqa: E501

        :return: The tag_expiration_s of this UpdateUser.  # noqa: E501
        :rtype: int
        """
        return self._tag_expiration_s

    @tag_expiration_s.setter
    def tag_expiration_s(self, tag_expiration_s):
        """Sets the tag_expiration_s of this UpdateUser.

        The number of seconds for tag expiration  # noqa: E501

        :param tag_expiration_s: The tag_expiration_s of this UpdateUser.  # noqa: E501
        :type: int
        """

        self._tag_expiration_s = tag_expiration_s

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateUser, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateUser):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
